import type { Metadata } from "next";
import "./globals.css";
import { Caveat, Montserrat } from "next/font/google";
import { QueryProvider } from "@/context/QueryProvider";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-caveat",
});

export const metadata: Metadata = {
  title: "BrushStroke",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body className={`${montserrat.variable} ${caveat.variable} relative`}>
          <main className="w-full mx-auto min-h-screen">{children}</main>
          <Toaster />
        </body>
      </QueryProvider>
    </html>
  );
}

//  px-4
